### ISSUE TITLE
Set up GitHub Actions for scheduled data fetch and upload to backend

### ISSUE THREAD

**Issue by Elieez** [Elieez/AktieKoll#15]
## Background
CSVFetchService fetches data, parses it into models, and sends POST requests to the backend API to update the database. The Next.js frontend uses GET endpoints to display data.

## Task
Automate fetching and uploading of new data every 30 minutes using GitHub Actions, with the following setup:

### Requirements
- Create a GitHub Actions workflow that runs every 30 minutes (`cron: '*/30 * * * *'`).
- Workflow should:
  - Checkout the repository.
  - Restore and build the C# project containing CSVFetchService.
  - Run the CSVFetchService as a CLI or entrypoint that fetches new data and posts it to the backend POST endpoint.
  - Use repository secrets for sensitive config (POST endpoint URL, API key, etc).
- Backend API endpoints must be deployed and accessible from GitHub Actions runners.
- POST endpoint should require an API key or other authentication for security.

### Security
- Use GitHub Secrets for endpoint URL and API key.
- Do not expose sensitive data in logs.

### Deliverables
- A `.github/workflows/fetch-and-upload-data.yml` workflow file (example below).
- Documentation/README updates if needed.

### Example workflow:
```yaml
name: Fetch and Upload Data Every 30 Minutes
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  fetch-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build project
        run: dotnet build --configuration Release
      - name: Run CSVFetchService and upload data
        run: dotnet run --project src/YourProjectWithCsvFetchService.csproj --environment Production
        env:
          POST_ENDPOINT_URL: ${{ secrets.POST_ENDPOINT_URL }}
          API_KEY: ${{ secrets.API_KEY }}
```
- Replace `src/YourProjectWithCsvFetchService.csproj` with your actual project path.
- Ensure deploy/host your backend API endpoints.
- Secure the POST endpoint.
